### ISSUE TITLE
Некорректная обработка незакрытых тэгов

### ISSUE THREAD

**Issue by Stepan-lab** [AssyaVl/githtmlfilter#1]
При подаче программе на вход следующей разметки html:
```html
<div id="main-content">
    text
    <style>
</div>

```
Программа не удаляет не закрытый тэг style.
Ожидается:
```html
<div id="main-content">
    text
</div>
```
Возвращается:
```html
<div id="main-content">
    text
    <style>
</div>
```

**Comment by staretc** [comment]
Цель проекта - исправление избыточной вёрстки и неправильного оформления HTML-кода.

Функционал проекта не рассчитан на обработку некорректного кода.
