### ISSUE TITLE
Программа крашится при недостаточном количестве аргументов

### ISSUE THREAD

**Issue by Kolka2** [AssyaVl/githtmlfilter#3]
## Описание

Программа вылетает, когда на вход подаётся один аргумент.

## Как воспроизвести

```bash
php ./HtmlFormatter.php simple.html
```

## Ожидаемое поведение

Программа выведет сообщение об ошибке и корректно завершит свою работу.

**Comment by staretc** [comment]
Обработка некорректного ввода была добавлена.
